image: docker:stable
services:
  - docker:stable-dind

before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}

.build:
  variables:
    TAG: "null"
  script:
    - docker build --pull --build-arg=TAG=${TAG} -t "${CI_REGISTRY_IMAGE}:${TAG}" .
    - docker push "${CI_REGISTRY_IMAGE}:${TAG}"
  only:
    - master

build-master-3.9:
  extends: .build
  stage: build
  variables:
    TAG: "3.9"

build-master-3.10:
  extends: .build
  stage: build
  variables:
    TAG: "3.10"

build-master-3.11:
  extends: .build
  stage: build
  variables:
    TAG: "3.11"

build-master-edge:
  extends: .build
  stage: build
  variables:
    TAG: "edge"

build:
  stage: build
  variables:
    TAG: "edge"
  script:
    - docker build --pull --build-arg=TAG=${TAG} -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  except:
    - master
