stages:
  - build

# Common variables
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"

# Build templates
.build:
  stage: build
  image: docker:stable
  services:
    - name: docker:stable-dind
      command: ["--experimental"]
  variables:
    BUILD_TAG: ""
    DOCKER_TAG: ""
  tags:
    - docker
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - docker build --pull --platform "linux/amd64" --build-arg="TAG=${BUILD_TAG}" -t "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-amd64" .
    - docker build --pull --platform "linux/arm64" --build-arg="TAG=${BUILD_TAG}" -t "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-arm64" .
    - docker build --pull --platform "linux/arm/v7" --build-arg="TAG=${BUILD_TAG}" -t "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-armv7" .
    - docker manifest create "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}" "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-amd64" "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-arm64" "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}-armv7"
    - docker push "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}"
  only:
    - master

# Jobs
# Alpine 3.9
build_master_3.9:
  extends: .build
  variables:
    BUILD_TAG: "3.9"
    DOCKER_TAG: "3.9"

# Alpine 3.10
build_master_3.10:
  extends: .build
  variables:
    BUILD_TAG: "3.10"
    DOCKER_TAG: "3.10"

# Alpine 3.11
build_master_3.11:
  extends: .build
  variables:
    BUILD_TAG: "3.11"
    DOCKER_TAG: "3.11"

# Alpine edge
build_master_edge:
  extends: .build
  variables:
    BUILD_TAG: "edge"
    DOCKER_TAG: "edge"

# PRs/branches
build_ci:
  extends: .build
  variables:
    BUILD_TAG: "edge"
    DOCKER_TAG: "${CI_COMMIT_SHORT_SHA}"
  only:
  except:
    - master
