name: ci

on:
  schedule:
    - cron: '22 12 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: saltydk/alpine-s6overlay
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          cache: true
          cache_registry: saltydk/cache
          debug: true
