#!/usr/bin/with-contenv sh

groupmod -o -g "${PGID:-911}" abc
usermod -o -u "${PUID:-911}" abc

echo "
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

chown abc:abc /app /config /defaults
